### ISSUE TITLE
Sample on main page shows wrong API

### ISSUE THREAD

**Issue by ReedCopsey** [ReedCopsey/Gjallarhorn#12]
It shows `Signal.subscribe` instead of `Signal.Subscription.create`

**Comment by FoggyFinder** [comment]
I don't understand why there is a label "bug". Isn't it enough to change this line?:
https://github.com/ReedCopsey/Gjallarhorn/blob/master/docs/content/index.fsx#L27

**Comment by ReedCopsey** [comment]
Yeah, but until I redo docs, it's wrong

**Comment by s952163** [comment]
This one can be closed, right?
