### ISSUE TITLE
Documentation right-side navigation could use fleshing out

### ISSUE THREAD

**Issue by mattstermiller** [ReedCopsey/Gjallarhorn#17]
The right-side navigation on the docs page could use the same links on the home page so that the user can always see what's there and jump around.

![image](https://cloud.githubusercontent.com/assets/2790867/19948591/557cdb58-a11b-11e6-99d7-e74780883e2c.png)

**Comment by mattstermiller** [comment]
#18

**Comment by ReedCopsey** [comment]
Will close when I regenerate docs, and the site's up to date.  Thank you @mattstermiller !
