### ISSUE TITLE
samples\WpfSimpleMvvmApplication.exe crashes when the `Do Async Op` button is clicked

### ISSUE THREAD

**Issue by s952163** [ReedCopsey/Gjallarhorn#22]
**samples\WpfSimpleMvvmApplication.exe crashes when the `Do Async Op` button is clicked**

Other samples work. WpfSimpleMvvmApplication.exe works until `Do Aysnc Op` is clicked, then crashes with the following exception:

> > .\WpfSimpleMvvmApplication.exe
> Names in "model" [1]: Recent [dsadssa dasdasd]
> 
> Unhandled Exception: System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
>    at Microsoft.FSharp.Control.CancellationTokenOps.Start@1224-1.Invoke(Exception e)
>    at <StartupCode$FSharp-Core>.$Control.loop@425-40(Trampoline this, FSharpFunc`2 action)
>    at Microsoft.FSharp.Control.Trampoline.ExecuteAction(FSharpFunc`2 firstAction)
>    at Microsoft.FSharp.Control.TrampolineHolder.Protect(FSharpFunc`2 firstAction)
>    at <StartupCode$FSharp-Core>.$Control.-ctor@510-1.Invoke(Object state)
>    at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()
>    at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
> Names in "model" [2]: Recent [adsadssa dasdasd]

Both in win7 and win10, built with VS2015. Let me know if you need further information.

**Comment by ReedCopsey** [comment]
@s952163 Corrected this.  The rewrite of the notification system broke the marshaling back to the UI context in the Idle Tracker.  It's been corrected now.

**Comment by s952163** [comment]
Wow, that was fast! :+1: Thank you!
