### ISSUE TITLE
Changing license to MIT

### ISSUE THREAD

**Issue by ReedCopsey** [ReedCopsey/Gjallarhorn#24]
I've had a couple of requests for this. I'm completely open to it, but would like to make sure the other contributors are okay with a license change.

@jeroldhaas , @TeaDrivenDev , @JohanLarsson , and @s952163 : 

Would you all please reply here if you're okay with changing the license to an MIT style license?

Thank you,
Reed

**Comment by JohanLarsson** [comment]
Fine with me.

**Comment by TeaDrivenDev** [comment]
I hereby release something something MIT license. ;-)

**Comment by s952163** [comment]
Cool!

**Comment by jeroldhaas** [comment]
Yes yes MIT 👍👍👍

**Comment by ReedCopsey** [comment]
Great - Thank you all!
