### ISSUE TITLE
Should we add async commanding support?

### ISSUE THREAD

**Issue by ReedCopsey** [ReedCopsey/Gjallarhorn#3]
Originally, I had planned to add support for async "commands", but I'm not sure it's necessary.

Since the command is really just a channel into the VM, there's nothing preventing starting an async operation explicitly.  We could even potentially create a signal mapper that worked asynchronously, which would let you directly subscribe in an async manner.

The biggest advantage of building it in would be the ability to hook into the execution tracker automatically (which is already written, but unused currently).  That could always be handled via the signal mapper, though.

I'd love to get input on this.  Would you rather have a set of APIs for commands that are async directly, or just leave it more explicit?

**Comment by ReedCopsey** [comment]
See #4 for potential alternatives, using signal functions directly.

**Comment by JohanLarsson** [comment]
Out of curiosity, what does the alternative look like in code?
We added async commands to or our stuff and it has been great.
We wrote them like this, sry about the c#:
```
public class AsyncCommand : ICommand
{
    public AsyncCommand(Func<Task> action) {...}
    
    public AsyncCommand(Func<CancellationToken, Task> action) {...}

    public ICommand CancelCommand { get; }
}
```

**Comment by ReedCopsey** [comment]
Well, my normal "command" in Gjallarhorn is different than a typical RelayCommand - you don't pass the function to execute, only the signal that determines the CanExecute on the command.

Instead, a command acts more like an observable - it's a channel you use to pipe notifications into the VM.  The logic happens in a subscription or through mappings - just like any other signal.

I'm thinking the actual usage would be more like:

```fsharp
let someAsyncFn _ =
    async {
        // Do something async
    }

let asyncCommand = subject.CommandChecked "AsyncCommand" subject.IdleTracker

let subscriptionHandle =
    asyncCommand
    |> Command.subscribeAsyncTracked someAsyncFn subject.IdleTracker
```

(This could, of course, be pushed into one binding, etc - but just showing the pieces.

**Comment by ReedCopsey** [comment]
This is now implemented. Added some observable utilities, which now allows for:

```fsharp
command
|> Observable.mapAsyncTracked asyncMapping subject.IdleTracker
|> subject.AddDisposable
```

This allows you to easily handle commands with an `'a -> Async<'b>`, and do tracking at the same time.
