### ISSUE TITLE
Create Navigation system for Framework

### ISSUE THREAD

**Issue by ReedCopsey** [ReedCopsey/Gjallarhorn#31]
The framework needs a mechanism to support navigation.  I'd like open a discussion about the best way to approach this before I try to implement something.

My goals would include:

 - Allow current framework message system to "update" navigation status
 - Allow "pages" to be pushed/popped from the navigation system via the message
 - Allow each page to be tied to a component, which would allow them to be developed in isolation
 - Allow each platform to override provided default mechanism for swapping out "page" [ie: make this usable in WPF via windows/dialogs/etc, as well as Xamarin Forms]

I'd love feedback on needs/wants/etc in order to start brainstorming on the best approach here.

**Comment by ReedCopsey** [comment]
@willsam100 I'd love any feedback you might have on this, as well.

**Comment by willsam100** [comment]
Just to document a couple of things discussed in over chat:
- Avoid (if possible) circular dependencies declaring Component with msg and model
- A mapping between Pages and Components would need to given to the framework during construction

Things to consider:
How many update functions to have e.g. one per app or one per component. I've built an app with one, but this could be the cause of circular dependencies.

**Comment by 7sharp9** [comment]
A single update cycle in an app often leads to too many concerns all in one place and also makes the logic loop involved rather large.  I would prefer a series of coordinators which act as the navigation between the various parts of the app.

**Comment by 7sharp9** [comment]
The other problem is abstracting the navigation, the differing systems make this pretty hard to do.  I know Xamarin Forms attempts this, albeit in a fairly naive manner, its not that suitable for an intuitive platform facing app.

**Comment by ReedCopsey** [comment]
Moving to https://github.com/ReedCopsey/Gjallarhorn.Bindable/issues/3 , since it belongs in that project.
