### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by majorgreys** [ReedCopsey/Gjallarhorn#35]
After a fresh clone of the git repoistory, I ran `build.cmd` from Powershell. But I get several build errors:

[Gjallhorn-build.txt](https://github.com/ReedCopsey/Gjallarhorn/files/1170308/Gjallhorn-build.txt)

I have "Microsoft Visual C++ Build Tools" version 14.0.25420.1 installed, which is what it seems gets used for the build command.

```
> cd "C:\Program Files (x86)\MSBuild\14.0\Bin\"
> .\MSBuild.exe /version
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

14.0.25420.1
```

I also have VS 2017 (along with the build tools) and dotnet installed:

```
> Get-VSSetupInstance

InstanceId          : 1eff422b
DisplayName         : Visual Studio Community 2017
InstallationVersion : 15.0.26430.16
InstallationPath    : C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
InstallDate         : 2017-06-28 6:37:15 PM

InstanceId          : d49f017f
DisplayName         : Visual Studio Build Tools 2017
InstallationVersion : 15.0.26430.16
InstallationPath    : C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
InstallDate         : 2017-07-22 2:00:32 PM
> dotnet --version
1.0.4
```

**Comment by majorgreys** [comment]
This issue was initially due to an older version of FAKE being specified in the paket.lock file. After running `.paket\paket.exe update` the build uses the VS2017 Community MSBuild.exe.

But now I'm getting another series of compile errors:

[Gjallhorn-build-2.txt](https://github.com/ReedCopsey/Gjallarhorn/files/1170442/Gjallhorn-build-2.txt)

**Comment by TeaDrivenDev** [comment]
Looks like it can't find a PCL compatible version of FSharp.Core. I can build it on both of my machines (with `Solution=NoAndroid`), but both have VS 2015 installed as well (not sure what difference that makes). However, FSharp.Core shows up as missing in Visual Studio on the PCL projects. Odd.

**Comment by TeaDrivenDev** [comment]
And I can only build it from FAKE; in Visual Studio I also get errors about lots of missing types.

**Comment by ReedCopsey** [comment]
This should be resolved completely. Let me know if you still have issues using the latest.
