### ISSUE TITLE
Page with Samle tutorial is out of date

### ISSUE THREAD

**Issue by BentTranberg** [ReedCopsey/Gjallarhorn#36]
This page seems to be outdated. It is linked on the other pages as "GETTING STARTED / Sample tutorial". At least I cannot find the View module referenced, and it looks like it was later renamed to Signal.

http://reedcopsey.github.io/Gjallarhorn/tutorial.html

Is the last example on that page, with the computation expression - is that still usable in some form?

The page seems to have been replaced with the very similar page intro.htm (link below), so that the only remaining todo is to remove the page named tutorial.html, and the links to it from other pages. Perhaps the link can be replaced with a link to the examples in the repo instead.

http://reedcopsey.github.io/Gjallarhorn/intro.html

**Comment by ReedCopsey** [comment]
Thank you @BentTranberg - Now corrected (and old tutorial page is now 404)
