### ISSUE TITLE
Problem with loading resources in Wpf.Framework 

### ISSUE THREAD

**Issue by FoggyFinder** [ReedCopsey/Gjallarhorn#37]
When using the framework, resources from `Application` not setting correctly

```fsharp
let main _ =
    Components.appComponent
    |> Gjallarhorn.Wpf.Framework.runApplication App MainWindow
```

Problem is here: https://github.com/ReedCopsey/Gjallarhorn/blob/master/src/Gjallarhorn.Bindable.Wpf/Wpf.fs#L50-L52

Workaround

```fsharp
let main _ =
    let app = App()
    Components.appComponent
    |> Gjallarhorn.Wpf.Framework.runApplication (fun () -> app) MainWindow
```

**Comment by ReedCopsey** [comment]
This will be fixed in the next build
