### ISSUE TITLE
Async Signal handling

### ISSUE THREAD

**Issue by ReedCopsey** [ReedCopsey/Gjallarhorn#4]
Right now, signal mapping/filtering/etc is always synchronous.

To go async, the best option (currently) is to treat it as an observable, and use Rx to do the processing, then map back into a signal if needed later.

We could add a set of async signal processing options, perhaps in their own submodule, ie: `SIgnal.Async.map` or similar.  These would likely need to work like filtering, where you specify the initial value for the resulting signal, since there wouldn't otherwise be a value until the operation completed.

**Comment by jeroldhaas** [comment]
Got my :+1:

**Comment by ReedCopsey** [comment]
Put first initial prototype in place:

https://github.com/ReedCopsey/Gjallarhorn/blob/master/samples/WpfSimpleMvvmApplication/ViewModels.fs#L71-L77

It's rough, but the basic concept is working now.  Need to see how to best handle this.

I suspect an async "subscription" is probably more valuable than the async mapping operation for most use cases.
