### ISSUE TITLE
Request for Feedback: Update

### ISSUE THREAD

**Issue by ReedCopsey** [ReedCopsey/Gjallarhorn#40]
The basic framework for applications already makes threading very simple. 

Some of the sample applications use thread-safe mutables for their internal state, which allows for completely thread safe pushing of update messages into the main application state. 

In addition, the framework already marshals model changes to the UI thread automatically.

Given this, I'm considering making the basic application do this automatically - so _all_ updates happen on a threadpool thread, and the UI is automatically fed the new model on the UI thread. This would effectively keep the UI thread decoupled from the entire "application logic", so all updates would happen off the UI thread _without any effort from the user_.

Note that this is an extremely small change, in terms of code. I've pushed it, as it appears to work perfectly in my testing. Changes required can be seen here: https://github.com/ReedCopsey/Gjallarhorn/commit/bdc882b8109dbdec16f1933260f28c4028d536f0

Does anybody see any disadvantages (significant or insignificant) to doing this automatically? I could potentially make it optional, but hate the thought of adding options for no reason.

**Comment by ReedCopsey** [comment]
Only downside I see, right now, is that (at least with this implementation) the message processing isn't serialized - it's effectively asynchronously updated per message, which could change the order of messages going to the update function. I'm not sure if that's really a problem, but would be curious as to thoughts.

I could, fairly easily, route the observables through a mailbox processor to keep them serialized, however. That would keep the order the same at the cost of some efficiency, which might be worthwhile here.

**Comment by s952163** [comment]
I think this is safer.

**Comment by s952163** [comment]
I can build the Gjallarhorn binaries, but some of the tests appear to fail, just FYI:

```
***** Gjallarhorn.Tests.Validate.Signal\validate works on value

Tests run: 181, Errors: 0, Failures: 1, Inconclusive: 0, Time: 1.35364357094854 seconds
  Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0

Errors and Failures:
1) Test Failure : Gjallarhorn.Linq.Tests.SignalLinq.SelectAsyncTracksProperly
     Expected: True
  But was:  False

at Gjallarhorn.Linq.Tests.SignalLinq.<SelectAsyncTracksProperly>d__11.MoveNext() in C:\Users\s9951_000\Documents\Source\Gjallarhorn\tests\Gjallarhorn.Linq.Tests\SignalLinq.cs:line 188
at NUnit.Framework.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
at NUnit.Core.NUnitAsyncTestMethod.RunTestMethod()
```

**Comment by ReedCopsey** [comment]
@s952163 Is that with the latest? It's green here...

**Comment by ReedCopsey** [comment]
After playing with this more, I think I'm going to move forward with leaving this in for vNext
