### ISSUE TITLE
Elm module

### ISSUE THREAD

**Issue by bcachet** [ReedCopsey/Gjallarhorn#41]
Hello,

I have written a module based on Gjallarhorn to write WPF application in a Unidirectional Flow approach (like Elm)
```fsharp
namespace Elm

open Gjallarhorn
open Gjallarhorn.Bindable
open Gjallarhorn.Wpf

open System

type ViewBinding<'model, 'msg> = BindingSource -> ISignal<'model> -> IObservable<'msg> option
type ViewBindings<'model, 'msg> = ViewBinding<'model, 'msg> list


module ViewBindings =
    let toComponent (viewBindings : ViewBindings<'model, 'msg>) : Component<'model, 'msg> =
        (fun source model ->
        viewBindings
        |> List.map (fun vb -> (vb source model))
        |> List.where Option.isSome
        |> List.map Option.get)



module Bindings =
    let private wrapRO getter f : ViewBinding<'model, 'msg> = 
        (fun (source : BindingSource) (model : ISignal<'model>) ->
                model
                |> Signal.map getter
                |> (f source)
                None)

    let private wrapRW getter setter f : ViewBinding<'model, 'msg> = 
        (fun (source : BindingSource) (model : ISignal<'model>) ->
            model
            |> Signal.map getter
            |> (f source)
            |> Observable.filter Option.isSome
            |> Observable.map Option.get
            |> Observable.map setter
            |> Some)

    let vm (getter : 'model -> 'a) (setter : 'b -> 'msg) (comp : ViewBindings<'a, 'b>) name : ViewBinding<'model, 'msg> =
        wrapRW getter setter (fun source  model-> Gjallarhorn.Bindable.Binding.componentToView source name (ViewBindings.toComponent comp) model |> Observable.map Some)

    let vmCollection getter setter (comp : ViewBindings<'a, 'b>) name : ViewBinding<'model, 'msg> = 
        (fun source (model : ISignal<'model>) ->
            let models = model |> Signal.map (getter >> Seq.mapi (fun i m -> m, i))
            let c s m = ViewBindings.toComponent comp s (Signal.map fst m)
            BindingCollection.toView source name models c 
            |> Observable.map (fun (msg,(m, id)) -> setter msg id)
            |> Some)

    let oneWay getter name : ViewBinding<'model, 'msg> =
        wrapRO getter (fun source -> Gjallarhorn.Bindable.Binding.toView source name)
        
    let twoWayConverted getter setter conversion name : ViewBinding<'model, 'msg> =
        wrapRW getter setter (fun source -> Binding.toFromViewValidated source name conversion)
        
    let twoWayValidated getter setter name : ViewBinding<'model, 'msg> =
        twoWayConverted getter setter Gjallarhorn.Validation.Converters.fromTo name

    let twoWay getter setter name : ViewBinding<'model, 'msg> =
        wrapRW getter setter (fun source model -> Binding.toFromView source name model |> Observable.map Option.Some)

    let cmd msg name : ViewBinding<'model, 'msg> =
        (fun (source : BindingSource) (model : ISignal<'model>) ->
            Gjallarhorn.Bindable.Binding.createMessage name msg source
            |> Some)

    let cmdIf msg canExecute name : ViewBinding<'model, 'msg> =
        (fun (source : BindingSource) (model : ISignal<'model>) ->
            Gjallarhorn.Bindable.Binding.createMessageChecked name (model |> Signal.map canExecute) msg source
            |> Some)

module App =            
    let app init update bindings : Framework.ApplicationCore<'model, 'msg> =
        Framework.basicApplication init update (bindings|> ViewBindings.toComponent)

    let run window app =
        Framework.runApplication System.Windows.Application window app

```

Complete code of the module and example of its usage can be found on https://github.com/bcachet/ElmAppliedToWPF

What do you think of this wrapper/module ?
Do I use Gjallarhorn correctly in this scenario ?

By showing you this module, I hope to:
 * improve my Gjallarhorn usage
 * get feedback on my approach

Have a nice day

Bertrand

**Comment by TeaDrivenDev** [comment]
Why do you define your functions (such as `wrapRO` and `wrapRW` using lambdas? That looks a little odd in F#.

**Comment by bcachet** [comment]
I wanted to emphasis that these methods generate ViewBinding<'model, 'msg>
Any idea to improve readability is welcomed

**Comment by ReedCopsey** [comment]
This is interesting. I've been trying to wrap my head around your wrappers (since Gjallarhorn's framework already acts unidirection).

From what I can see, the main benefit here is getting rid of working with the BindingSource/Model, and focusing on the "getter" and "setter" when mapping through the data bindings. I think some of this could be integrated into the core framework (esp. since I'm looking at making some changes there) - I definitely see some of the benefits with regards to simplicity.

**Comment by ReedCopsey** [comment]
Looking more - I'm not sure why ViewBinding is an option. Was that mainly so you could include `oneWay` in the list? It definitely adds some unnecessary overhead - and I'm trying to think about ways that could be eliminated cleanly.

**Comment by bcachet** [comment]
You are right. Option was to distinguish ReadOnly/ReadWrite components or in other words components that generate Observable or not.

Do you need my help to integrate this wrappers inside Gjallarhorn ? If so, have you any requirements on how to integrate them ?

**Comment by ReedCopsey** [comment]
@bcachet So - I'm taking some inspiration from this, and looking at breaking Gjallarhorn's API and integrating these ideas into "v2"

I've been working on eliminating the magic strings, as well. I'd love your take on the following.  Right now, I've been working on rethinking/reworking how this example is done: https://github.com/ReedCopsey/Gjallarhorn/blob/master/samples/ElmInspiredOne/ElmInspiredOne/Program.fs#L32-L41

My current version looks like the following:

```fsharp
namespace ElmInspiredOne

open Gjallarhorn.Bindable

// Note that this program is defined in a PCL, and is completely platform neutral.
// It will work unchanged on WPF, Xamarin Forms, etc
module Program =    
    // ----------------------------------     Model     ---------------------------------- 
    // Model is a simple integer for counter
    type Model = int
    let initModel i : Model = i

    // ----------------------------------    Update     ---------------------------------- 
    // We define a union type for each possible message
    type Msg = 
        | Increment 
        | Decrement

    // Create a function that updates the model given a message
    let update msg (model : Model) : Model =
        match msg with
        | Increment -> min 10 (model + 1)
        | Decrement -> max 0 (model - 1)

    // Our "ViewModel". This is optional, but allows you to avoid using "magic strings", as well as enables design time XAML in C# projects
    type ViewModel = 
        {
            Current : Model 
            Increment : Cmd<Msg>
            Decrement : Cmd<Msg>
        }    

    // This is our design/compile time ViewModel used for XAML and binding for naming
    let d = { Current = 5 ; Increment = Cmd Increment; Decrement = Cmd Decrement }
         
    // ----------------------------------    Binding    ---------------------------------- 
    // Create a function that binds a model to a source, and outputs messages
    // This essentially acts as our "view" in Elm terminology, though it doesn't actually display 
    // the view as much as map from our type to bindings
    let bindToSource =           
        // Create our bindings - the VM type defines the name, the Bind call determines the type of data binding
        [
            <@ d.Current    @> |> Bind.oneWay id
            <@ d.Increment  @> |> Bind.cmdIf (fun v -> v < 10)
            <@ d.Decrement  @> |> Bind.cmdIf (fun v -> v > 0)
        ]         
    // let appComponent = Component bindToSource

    // ----------------------------------   Framework  -----------------------------------     
    let applicationCore = Framework.basicApplication (initModel 5) update bindToSource
```

I'm curious what you think of this as a potential "primary" API moving forward. I'm considering taking the current approach (which is more flexible) and moving it to a separate namespace to work in untyped/string form if you need the flexibility, and having a "clean" API be the default.

**Comment by bcachet** [comment]
Your approach offer the flexibility to have optional ViewModel to avoid magic string and being able to define DataContext in Xaml.
I really like the ViewModel approach. It will help use to use all the features of WPF tools which require ViewModel.
In the end, we use Unidirectional Flow to update our Model, and create a ViewModel to satisfy WPF framework. The View part of Elm is our ViewModel.

Defining the ViewModel can be verbose. Maybe we can create modules/types to simplify this part.

Really nice work

**Comment by ReedCopsey** [comment]
I think the verbosity issue will solve itself. Theres a language feature approved for f# 4.2 that simplifies it... Anonymous records. That lets you define the design time type in one line, without having to write out the VM, and should work from xaml tooling and the quotations. The ViewModel makes a good interim solution.

**Comment by bcachet** [comment]
👌



--
Bertrand

. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
☎: +41 78 664 20 88
🏠: Route de Neuchâtel 3; 2520 La Neuveville; Switzerland

**Comment by ReedCopsey** [comment]
Alright - I'm going to close this issue (for now) - Work is underway for vNext which will include a variation of this.

@bcachet  If you want to discuss further, I'm happy to chat on the F# Software Foundation slack team - I'm on there frequently (and often chatting about Gjallarhorn :) ) Would love to be able to bounce ideas off you in real time occasionally.

**Comment by MangelMaxime** [comment]
The vNext api looks really good 👏

**Comment by ReedCopsey** [comment]
@bcachet Just pushed this as a prerelease to NuGet https://www.nuget.org/packages/Gjallarhorn.Bindable.Wpf/1.0.0-beta1- Let me know what you think!

Still going to work on nav support before an official release, I think - I pretty sure I have an approach locked in
