### ISSUE TITLE
Add a sample walkthrough which documents how to bind signals in a simple app using this lib

### ISSUE THREAD

**Issue by 7sharp9** [ReedCopsey/Gjallarhorn#45]
One of the things I find with this library is the documentation is too simplistic and not representative use in an application etc.

**Comment by voronoipotato** [comment]
Given that it's been like 4 months since you've posted this and had no response if you figure it out would you mind doing a writeup?

**Comment by ReedCopsey** [comment]
I'd recommend looking at the samples in Gjallarhorn.Bindable, which shows this being used in "real applications" that are a lot more elaborate. https://github.com/ReedCopsey/Gjallarhorn.Bindable/tree/master/samples
