### ISSUE TITLE
What is blocking creating signals from the standard mutables

### ISSUE THREAD

**Issue by voronoipotato** [ReedCopsey/Gjallarhorn#53]
Hey I saw this and it looks really awesome, but I was curious what is basically preventing you from having a signal subscribe to a normal standard mutable.

# Example
```fsharp
let mutable x = 0
Signal.Subscription.create (fun currentValue -> printfn "Value is now %d" currentValue) m 

// After this is set, a print will occur
// Prints: "Value is now 1"
m.Value <- 1

// After this is set, a second print will occur with the new value
// Prints: "Value is now 2"
m.Value <- 2
```

**Comment by TeaDrivenDev** [comment]
How would you detect the change? There is no built-in notification on updates of simple mutable "variables" in .NET. (Which is mostly why it needs the whole `INotifyPropertyChanged` story in the first place.)

**Comment by ReedCopsey** [comment]
That's exactly it. There is no notification mechanism on variables in .net. The only approach I can think of that's approximate what you have would involve polling the value.

**Comment by voronoipotato** [comment]
Thanks for taking the time to answer my question :).

**Comment by amieres** [comment]
You should check the way WebSharper.UI.Next works
https://github.com/dotnet-websharper/ui/blob/master/docs/UINext-Dataflow.md

**Comment by voronoipotato** [comment]
This technique requires Var.Create

**Comment by amieres** [comment]
Correct, your code would translate to something like this:
```
let m = Var.Create 0

View.Sink (fun currentValue -> printfn "Value is now %d" currentValue) m.View

// After this is set, a print will occur
// Prints: "Value is now 1"
m.Value <- 1

// After this is set, a second print will occur with the new value
// Prints: "Value is now 2"
m.Value <- 2
```

**Comment by amieres** [comment]
Looks like it is a similar approach to Gjallarhorn
