### ISSUE TITLE
Errors in CoreTypes.fs

### ISSUE THREAD

**Issue by majocha** [ReedCopsey/Gjallarhorn#58]
According to these comments
https://github.com/Microsoft/visualfsharp/issues/5286#issuecomment-402249997
>Because |> is a generic function, the rules state you can't have a byref<_> as a type arg

https://github.com/Microsoft/visualfsharp/issues/5270#issuecomment-401875011
> Local functions and lambdas cannot have byref-like parameters

there are now some restrictions when using byref.

Opening Gjallarhorn project in Rider or Visual Studio I'm getting a lot of errors:
![image](https://user-images.githubusercontent.com/1760221/50252175-72821580-03e6-11e9-9f92-ffcf471f1d80.png)

The message is not very helpful

![image](https://user-images.githubusercontent.com/1760221/50252250-a8bf9500-03e6-11e9-859a-3881e5229cc5.png)

but it seems that partial application doesn't work with byref anymore.

This form makes the error go away:
![image](https://user-images.githubusercontent.com/1760221/50252290-cbea4480-03e6-11e9-8411-56dd6c456ae2.png)

**Comment by ReedCopsey** [comment]
Thank you for this. Was a change in F# that happened with all of the span work, I believe.
