### ISSUE TITLE
How to build the project?

### ISSUE THREAD

**Issue by charlesroddie** [ReedCopsey/Gjallarhorn#64]
On attempting to build the project or solution I get these errors:

![image](https://user-images.githubusercontent.com/19760720/103345965-b5256080-4a8a-11eb-98fa-c79680e3ee92.png)

**Comment by FoggyFinder** [comment]
1. Run `build.cmd` (paket will be downloaded).
2. VS: Restore NuGet package
3. VS: Rebuild
